dist: bionic

language: scala

scala:
  - "2.12.12"

jdk: oraclejdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
    - $HOME/.sbt/launchers

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

install:
  - git fetch --tags

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalastyle test:scalastyle coverage test coverageReport scripted

before_script:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_82c15cb04022_key -iv $encrypted_82c15cb04022_iv -in secring.asc.enc -out secring.asc -d;
      gpg --batch --import secring.asc;
      gpg --list-secret;
      rm secring.asc;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned
    on:
      tags: false
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned sonatypeBundleRelease
    on:
      tags: true

env:
  global:
    - secure: "lg0z7sTC/i0+IjePIwd1dsgZi+RiN1kxahNVlUs/6T/IIJwvWOs3Uf6CXuughaebkbcC3iIk/kLAeU+WbKV0c/syf7vxzzzMtgjTge3m3k94Hjyo+JxvRyfpZ0d6GWVpyBfLdnOlq2myPeM79naxw7nPFlP1/s/rYmuARzWsjzKckDcjxRABTf5YEsqTunGSXBnBCjmejN0Rh8qL7e5XUKfRDL6wb3B/V3/gd6fZacv58jqRq2XyiAyO0YQxIbsBCS1g+EZudeakynkco5ci3JsdrqwC7pups/pm0T3/ftst5ZXOjKBHx7I1zMtsATL71ZD0bzI7PKLooRytIK4bAVtXQmC65wKSSe9Q4DrXPixOqFcu9ZYjU8ZjfaBfuPZfTK1Da9TBkTYNq1s+KTu07I7SK3lsSpRRrC4OT4jH1q9d6PnNf71iymHGgr5rcqgKJFD5TLEP1VpYgD6iNItIaIwgZ9smm7lfRG6lpe8hK92v0U/iPNFE4AKblmcCw8QekqZrvxyTPS4B7BmammGD9UCwhb1gMxfEPIP8/cWOyPPgKKT3EPzLyzDsePPnAjLgb4bHWf2jBMaVV3sbhPtY9Gzw/Q8UJScC/sGiaQ0cXeTS3FODe2D2ZOYFNal62c+/7tfqE7KxulMZ7QPYVBySrXEo9dAIJt65hiSWuDbmBJs="
    - secure: "jql048+uc86x9OdqjvMakL5Tk1Zl+bRZdL5sY30+jkBOXoPg0M5xwUgkaiCb+3Ak3rTHLX6TZ1tXBz0hH9DUXlUyS4bpTrr+/VSZR93wYfAe1kMwp6kflhPD7Y0Z3VYL/3r99/Y6kitYG+Cl0o27q3093ouvhXsRK0MkhwqR/0BDJc1+Akiwvi5kSVgufW4aeSyb3iReIxGldSLU/eVvzzUHBpL9uNWSx5KRIC1aiGtnQgnLtFbyT408rxb9oUVk+Rd+BtzY4GTLKeuYHXMvL8RmUlhJKDUbAV16eTLhE4byNYqSKsbE9chs8Aha7HMcyPNm3YMH6oG81oYYtF80G2VTkuH5dUV/WXSwAcGbiFP63wVxZsubLvtLP0ui8RT1KH7Y2q06lMivPPmHwcssY8Ew9mzmde+rgpk1H6XLZODKBqzsR6EVcMkkbl6t6fZ8dNFKQeiHHbByBH8emTv3ca9HUR9b9yPM/WdOcwLJItdPr6qn9Za4QvNGVSC4lE/m42TVY9NP8oYFgCaOAIezeEDIP726xH38DLTKAs1NLNc3wu3bjacOBQdeuwPuJmOEfYc+yx5Qn0dKrXRBDPGmjjV7f46P9Vgpp4ZntdyzN0INI4zT8hK7hcQL7qu2JlZq1K+RF/neFXczcK8B9urR2hhhvrvEHfZ23pJzXNj//RI="
    - secure: "m+87TVhc3A3qKlO5yNdNI//5km8piM8xXz5//A5wZ3NecUcaD6LF0L1ulnT+m14EdG3FQVm2pcxEUd2QcpgcDq7Q62ijaojZHNP/nZkaBPLHtylZgWrEitwZDVtKs8Hyl2MNsk73xpquXK72Qe/ipXT3vrmsEe1O/ugGOpcgztuGMvKXGT0sVx/ttN//YVyqhCqtH8Mj39r3ATDCKT/uVDwg27Ii5ADNlZ/lZ8BvB82vgv/rlurFWNfQ/yHT1cwY1ojLuzjZe0bWlYFYURsB1RkQaP5CMYJSI2NgtBpDn0zPs6csPrXXohwfedWmjLTgZU2UOj+oIBvrgy/Jpk2NpTArzdvtjEE5E9dNEZ2Of7qs55otG/WCNtAxzQPCnkKwBFArGrro0knR6CIKhrs+8qwTilNXmEuSk/sA7zXY6kpMvqLzph6ZNkiWRt5kkgsDX/5+7EFgwkKdEa47D1c8COUKm6kUDjOWDb0cjYj+8S21kyi+7o68ySNjq2JVIncg1ZqXVsonCh7RJ1Yi7ZWYGYujZoLO94V5ISWviKrbX7oLrTOuaO0NS3PavG/xHK26v4WQ5H16ToIkwRKPbd9wyMGEELJ3ySr0xhnZV36qkPgwIZUcill1USJ/e5+q/uHSdXN5cCLNR6UFnHyxClRe0XAARa653M86pflmBUlJtQA="
